# Pandas

![pandas](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExbzc4ZTFvZmZweTBzN2hnMGxpd3EyZW00dngwamdlNmxrZ2RndGRtMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l1KVcBV7rstepCYhi/giphy.gif)

## Installation

In [ ]:
# This script installs the pandas library using pip, this is here just in case
# you need to run it in an environment where pandas is not installed.
! pip install pandas

## Documentation

[https://pandas.pydata.org/docs/user_guide/index.html](https://pandas.pydata.org/docs/user_guide/index.html)

## Pandas Basics

### Importing Pandas

The Pandas library must always be imported on top of your script.

In [1]:
import pandas as pd

In [28]:
# Helper function to create a DataFrame
def create_dataframe():
    
    data = {
        'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']
    }

    return pd.DataFrame(data)

### Series

A Series is like a column in a table, a one-dimensional array used to hold data of any type.

In [2]:
# Create a Series with a list of numbers
aList = [1, 2, 3, 4, 5]

numbers = pd.Series(aList)

# Display the Series
print(aList)

[1, 2, 3, 4, 5]

It can also hold key/value pairs, like a dictionary.

In [3]:
# Create a Series with key-value pairs
aDict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

numbersDict = pd.Series(aDict)

# Display the Series    
print(numbersDict)

a    1
b    2
c    3
d    4
e    5
dtype: int64

### DataFrames

A DataFrame is a two-dimensional data structure, AKA a table with rows and columns.

In [29]:
# Create a DataFrame with some sample data
df = create_dataframe()

df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

Take note that the row index is displayed to the left of the DataFrame. Row indexes in Pandas start with 0 by default.

## Pandas Properties and Methods

### `loc` Property

`loc` returns a specific row in your DataFrame, this will return a Series

In [ ]:
# Create a DataFrame with some sample data
df = create_dataframe()

df.loc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

You can also return multiple rows by passing a list, this will return a DataFrame

In [6]:
df.loc[[0, 1]]

    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles

### Loading a DataFrame with Data

A locally saved CSV

In [7]:
# Path for the CSV file
filePath = 'data/ASPCDRS_2025-04-15_UID1327_1212206161_2025060900.csv'

df = pd.read_csv(filePath)

df.head() # Display the first 5 rows of the DataFrame, you can change the number inside head() to display more or fewer rows

,SourceId,CallDate,BilledCountry,BilledNumber,OtherCountry,OtherNumber,CarrierCode,SourceCustomerID,Seconds,IsTollFree,IsIncoming,Code,SourceType,IsPrerated,Charge,TimeZone,CarrierRateType
0,AS202506101841,2025-04-15 10:41,NaN,12122006161,NaN,15142340046,NaN,X012C003,6,NaN,0,NaN,Subscriber,0,NaN,EST,NaN
1,AS202506101840,2025-04-15 10:40,NaN,15144481212,NaN,15145009998,NaN,X012C003,6,NaN,0,NaN,Subscriber,0,NaN,EST,NaN
2,AS202506101839,2025-04-15 10:39,NaN,12122006161,NaN,15145009999,NaN,X012C003,6,NaN,0,NaN,Subscriber,0,NaN,EST,NaN
3,AS202506101838,2025-04-15 10:38,NaN,12122006161,NaN,16137559999,NaN,X012C003,6,NaN,0,NaN,Subscriber,0,NaN,EST,NaN
4,AS202506101837,2025-04-15 10:37,NaN,12122006161,NaN,14187229999,NaN,X012C003,6,NaN,0,NaN,Subscriber,0,NaN,EST,NaN

A locally saved JSON

In [8]:
filePath = 'data/Comparative.json' 

df = pd.read_json(filePath)

df.tail() # Display the last 5 rows of the DataFrame, you can change the number inside tail() to display more or fewer rows

,Date,Customer_Id,Customer_Name,MRC_Client,MRC_Rev,MRC_Diff,MRC_Abs_Diff,NRC_Client,NRC_Rev,NRC_Diff,...,Credits_Diff,Credits_Abs_Diff,Taxes_Client,Taxes_Rev,Taxes_Diff,Taxes_Abs_Diff,Total_Client,Total_Rev,Total_Diff,Total_Abs_Diff
123,2024-09-01,1100000270,Welders Supply Co/ Raimy Corp,356.42,356.42,0.0,0.0,0,0.0,0.0,...,0.0,0.0,140.99,185.66,44.67,44.67,497.41,542.08,44.67,44.67
124,2024-09-01,1100000260,Welsh Motor Sales Inc,1302.89,1253.89,-49.0,49.0,0,0.0,0.0,...,0.0,0.0,168.63,139.09,-29.54,29.54,1471.52,1392.98,-78.54,78.54
125,2024-09-01,1100000197,West Bradford Township,762.86,762.86,0.0,0.0,0,0.0,0.0,...,0.0,0.0,142.77,96.92,-45.85,45.85,923.18,859.78,-63.40,63.40
126,2024-09-01,1100000209,Windsor Nissan,1909.64,1909.64,0.0,0.0,0,0.0,0.0,...,0.0,0.0,668.33,685.83,17.50,17.50,2578.39,2595.86,17.47,17.47
127,2024-09-01,1100000358,World Logistics USA,643.19,643.19,0.0,0.0,0,0.0,0.0,...,0.0,0.0,119.54,246.25,126.71,126.71,770.52,897.10,126.58,126.58

A table from a Wikipedia, Pandas reads in the raw HTML and indexes the `<table>...</table>` tags

In [9]:
# Inspect the code from the URL below
url = 'https://en.wikipedia.org/wiki/List_of_Formula_One_World_Drivers%27_Champions'

# Read HTML from the specified URL
import requests
html = requests.get(url).text

print(html) # Display the HTML content retrieved from the URL

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" lang="en" dir="ltr">
<head>
<meta charset="UTF-8">
<title>List of Formula One World Drivers' Champions - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"96d4ded6-a198-41ba-9013-bce9456f0203","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_Formula_One_World_Drivers'_Champions","wgTitle":"List of Formula One World Drivers' Champions","wgCurRevisionId":1294301409,"wgRevisionId":1294301409,"wgArticleId":3437295,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Wikipedia semi-protected pages","Use dmy dates from January 2023","Pages using multiple image with auto scaled images","Official website not in Wikidata","Featured lists","Formula One drivers","Formula One World Drivers' Champions","Formula One-related lists","Lists of motorsport champions","Lists of auto racing people","Lists of sports world champions"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_Formula_One_World_Drivers'_Champions","wgRelevantArticleId":3437295,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["autoconfirmed"],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":90000,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[]},"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q172863","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.xLab","ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta name="ResourceLoaderDynamicStyles" content="">
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">
<meta name="generator" content="MediaWiki 1.45.0-wmf.6">
<meta name="referrer" content="origin">
<meta name="referrer" content="origin-when-cross-origin">
<meta name="robots" content="max-image-preview:standard">
<meta name="format-detection" content="telephone=no">
<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Schumacher_china_2012_crop.jpg/1200px-Schumacher_china_2012_crop.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="1677">
<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Schumacher_china_2012_crop.jpg/960px-Schumacher_china_2012_crop.jpg">
<meta property="og:image:width" content="800">
<meta property="og:image:height" content="1118">
<meta property="og:image:width" content="640">
<meta property="og:image:height" content="895">
<meta name="viewport" content="width=1120">
<meta property="og:title" content="List of Formula One World Drivers&#039; Champions - Wikipedia">
<meta property="og:type" content="website">
<link rel="preconnect" href="//upload.wikimedia.org">
<link rel="alternate" media="only screen and (max-width: 640px)" href="//en.m.wikipedia.org/wiki/List_of_Formula_One_World_Drivers%27_Champions">
<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">
<link rel="icon" href="/static/favicon/wikipedia.ico">
<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">
<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">
<link rel="canonical" href="https://en.wikipedia.org/wiki/List_of_Formula_One_World_Drivers%27_Champions">
<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">
<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">
<link rel="dns-prefetch" href="//meta.wikimedia.org" />
<link rel="dns-prefetch" href="auth.wikimedia.org">
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-List_of_Formula_One_World_Drivers_Champions rootpage-List_of_Formula_One_World_Drivers_Champions skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
	<header class="vector-header mw-header no-font-mode-scale">
		<div class="vector-header-start">
			<nav class="vector-main-menu-landmark" aria-label="Site">

<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >
	<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"  >
	<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>

<span class="vector-dropdown-label-text">Main menu</span>
	</label>
	<div class="vector-dropdown-content">


				<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">

<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">
	<div
	class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"
	data-feature-name="main-menu-pinned"
	data-pinnable-element-id="vector-main-menu"
	data-pinned-container-id="vector-main-menu-pinned-container"
	data-unpinned-container-id="vector-main-menu-unpinned-container"
>
	<div class="vector-pinnable-header-label">Main menu</div>
	<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
	<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>


<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >
	<div class="vector-menu-heading">
		Navigation
	</div>
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">

			<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
		</ul>

	</div>
</div>



<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >
	<div class="vector-menu-heading">
		Contribute
	</div>
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">

			<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>
		</ul>

	</div>
</div>

</div>

				</div>

	</div>
</div>

		</nav>

<a href="/wiki/Main_Page" class="mw-logo">
	<img class="mw-logo-icon" src="/static/images/icons/wikipedia.png" alt="" aria-hidden="true" height="50" width="50">
	<span class="mw-logo-container skin-invert">
		<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;">
		<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" width="117" height="13" style="width: 7.3125em; height: 0.8125em;">
	</span>
</a>

		</div>
		<div class="vector-header-end">

<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">
	<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>

<span>Search</span>
	</a>
	<div class="vector-typeahead-search-container">
		<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
			<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">
				<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">
					<div class="cdx-text-input cdx-text-input--has-start-icon">
						<input
							class="cdx-text-input__input mw-searchInput"
							 type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="sentences" spellcheck="false" title="Search Wikipedia [f]" accesskey="f" id="searchInput"
							>
						<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
					</div>
					<input type="hidden" name="title" value="Special:Search">
				</div>
				<button class="cdx-button cdx-search-input__end-button">Search</button>
			</form>
		</div>
	</div>
</div>

			<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">
	<div class="vector-user-links-main">

<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>


<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>

	<nav class="vector-appearance-landmark" aria-label="Appearance">

<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >
	<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"  >
	<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>

<span class="vector-dropdown-label-text">Appearance</span>
	</label>
	<div class="vector-dropdown-content">


			<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">

			</div>

	</div>
</div>

	</nav>

<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>


<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">
			<li id="pt-sitesupport-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" class=""><span>Donate</span></a>
</li>
<li id="pt-createaccount-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+Formula+One+World+Drivers%27+Champions" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>
</li>
<li id="pt-login-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+Formula+One+World+Drivers%27+Champions" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>
</li>


		</ul>

	</div>
</div>

	</div>

<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out"  title="Log in and more options" >
	<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"  >
	<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>

<span class="vector-dropdown-label-text">Personal tools</span>
	</label>
	<div class="vector-dropdown-content">



<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item"  title="User menu" >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


In [10]:
# Read all tables from the specified URL
df = pd.read_html(url)

# Loop through the tables and display the first 5 rows of each table
for i, table in enumerate(df):

    print(f"Table {i}:")

    print(table.head())  # Display the first 5 rows of each table
    
    print("\n")

Table 0:
                                                   0
0                This article is part of a series on
1                                        Formula One
2                                Current season 2025
3  Related articles History Weekend format Regula...
4  Lists Circuits Grands Prix Red-flagged races S...


Table 1:
      0                                                  1
0  Bold  indicates the constructor also won the Constru...


Table 2:
    Season                  Driver Age  Constructor             Tyres Poles  \
    Season                  Driver Age      Chassis      Engine Tyres Poles
0     1950     Giuseppe Farina[21]  44   Alfa Romeo  Alfa Romeo     P     2
1     1951  Juan Manuel Fangio[22]  40   Alfa Romeo  Alfa Romeo     P     4
2  1952[a]      Alberto Ascari[24]  34      Ferrari     Ferrari   F P     5
3  1953[a]      Alberto Ascari[24]  35      Ferrari     Ferrari     P     6
4     1954  Juan Manuel Fangio[22]  43  Maserati[b]    Maserati     P     5

  Wins Podiums Fastest laps Points          % Points  Clinched[17]  \
  Wins Podiums Fastest laps Points          % Points  Clinched[17]
0    3       3            3     30   83.333 (47.619)  Round 7 of 7
1    3       5            5     31   86.111 (51.389)  Round 8 of 8
2    6       6            6     36  100.000 (74.306)  Round 6 of 8
3    5       5            4   34.5   95.833 (57.407)  Round 8 of 9
4    6       7            3     42   93.333 (70.547)  Round 7 of 9

  # of rounds remaining  Margin % Margin
  # of rounds remaining  Margin % Margin
0                     0       3   10.000
1                     0       6   19.355
2                     2      12   33.333
3                     1     6.5   18.841
4                     2  16.857   40.136


Table 3:
               Driver  Titles                                 Season(s)
0  Michael Schumacher     7.0  1994, 1995, 2000, 2001, 2002, 2003, 2004
1      Lewis Hamilton     7.0  2008, 2014, 2015, 2017, 2018, 2019, 2020
2  Juan Manuel Fangio     5.0              1951, 1954, 1955, 1956, 1957
3         Alain Prost     4.0                    1985, 1986, 1989, 1993
4    Sebastian Vettel     4.0                    2010, 2011, 2012, 2013


Table 4:
          Country Titles Drivers  \
0  United Kingdom     20      10
1  United Kingdom     20      10
2  United Kingdom     20      10
3  United Kingdom     20      10
4  United Kingdom     20      10

                                             Seasons  By driver (titles)
0  1958, 1962–1965, 1968–1969, 1971, 1973, 1976, ...  Lewis Hamilton (7)
1  1958, 1962–1965, 1968–1969, 1971, 1973, 1976, ...  Jackie Stewart (3)
2  1958, 1962–1965, 1968–1969, 1971, 1973, 1976, ...       Jim Clark (2)
3  1958, 1962–1965, 1968–1969, 1971, 1973, 1976, ...     Graham Hill (2)
4  1958, 1962–1965, 1968–1969, 1971, 1973, 1976, ...   Jenson Button (1)


Table 5:
   Unnamed: 0              Driver                 Age  Season
0           1    Sebastian Vettel  23 years, 134 days    2010
1           2      Lewis Hamilton  23 years, 300 days    2008
2           3     Fernando Alonso   24 years, 58 days    2005
3           4      Max Verstappen   24 years, 73 days    2021
4           5  Emerson Fittipaldi  25 years, 273 days    1972


Table 6:
   Unnamed: 0              Driver                 Age  Season
0           1  Juan Manuel Fangio   46 years, 41 days    1957
1           2     Giuseppe Farina  43 years, 308 days    1950
2           3        Jack Brabham  40 years, 155 days    1966
3           4         Graham Hill  39 years, 262 days    1968
4           5       Nigel Mansell    39 years, 8 days    1992


Table 7:
   Championships              Driver    Seasons
0              5  Michael Schumacher  2000–2004
1              4  Juan Manuel Fangio  1954–1957
2              4    Sebastian Vettel  2010–2013
3              4      Lewis Hamilton  2017–2020
4              4      Max Verstappen  2021–2024


Table 8:
   Championships      Drivers[a]       Years
0              2   Nelson Piquet  1981, 1983
1              2  Max Verstappen  2021, 2024
2              1   Mike Hawthorn        1958
3              1  Jackie Stewart        1973
4              1      James Hunt        1976


Table 9:
       Constructor Titles                                          Season(s)
0          Ferrari     15  1952, 1953, 1956, 1958, 1961, 1964, 1975, 1977...
1          McLaren     12  1974, 1976, 1984, 1985, 1986, 1988, 1989, 1990...
2      Mercedes[a]      9  1954,[a] 1955, 2014, 2015, 2016, 2017, 2018, 2...
3  Red Bull Racing      8     2010, 2011, 2012, 2013, 2021, 2022, 2023, 2024
4         Williams      7           1980, 1982, 1987, 1992, 1993, 1996, 1997


Table 10:
     Manufacturer Titles                                          Season(s)
0         Ferrari     15  1952, 1953, 1956, 1958, 1961, 1964, 1975, 1977...
1         Ford[a]     13  1968, 1969, 1970, 1971, 1972, 1973, 1974, 1976...
2  Mercedes[b][c]     13  1954,[b] 1955, 1998, 1999, 2008, 2009, 2014, 2...
3      Renault[d]     11  1992, 1993, 1995, 1996, 1997, 2005, 2006, 2010...
4           Honda      6                 1987, 1988, 1989, 1990, 1991, 2021


Table 11:
   Rank Manufacturer Manufacturer.1      Titles  \
0     1            G       Goodyear   24 (7)[a]
1     2            P        Pirelli  20 (14)[b]
2     3            B    Bridgestone   11 (6)[e]
3     4            D         Dunlop    8 (4)[f]
4     5            M       Michelin           6

                                             Seasons
0  1966–1967, 1971, 1973–1978, 1980, 1982, 1985–1997
1                   1950–1954,[c][d] 1957, 2011–2024
2                               1998–2004, 2007–2010
3                                    1959–1965, 1969
4                   1979, 1981, 1983–1984, 2005–2006


Table 12:
             vteFormula One World Drivers' Champions  \
0  1950 G. Farina 1951 J. M. Fangio 1952 A. Ascar...
1                                                NaN

           vteFormula One World Drivers' Champions.1  \
0  1950 G. Farina 1951 J. M. Fangio 1952 A. Ascar...
1  1950 G. Farina 1951 J. M. Fangio 1952 A. Ascar...

                                          Unnamed: 2  \
0                                                NaN
1  1960 J. Brabham 1961 P. Hill 1962 G. Hill 1963...

                                          Unnamed: 3  \
0                                                NaN
1  1970 J. Rindt 1971 J. Stewart 1972 E. Fittipal...

                                          Unnamed: 4  \
0                                                NaN
1  1980 A. Jones 1981 N. Piquet 1982 K. Rosberg 1...

                                          Unnamed: 5  \
0                                                NaN
1  1990 A. Senna 1991 A. Senna 1992 N. Mansell 19...

                                          Unnamed: 6  \
0                                                NaN
1  2000 M. Schumacher 2001 M. Schumacher 2002 M. ...

                                          Unnamed: 7  \
0                                                NaN
1  2010 S. Vettel 2011 S. Vettel 2012 S. Vettel 2...

                                          Unnamed: 8
0                                                NaN
1  2020 L. Hamilton 2021 M. Verstappen 2022 M. Ve...


Table 13:
    0                                                  1  \
0 NaN  1950 G. Farina 1951 J. M. Fangio 1952 A. Ascar...

                                                   2  \
0  1960 J. Brabham 1961 P. Hill 1962 G. Hill 1963...

                                                   3  \
0  1970 J. Rindt 1971 J. Stewart 1972 E. Fittipal...

                                                   4  \
0  1980 A. Jones 1981 N. Piquet 1982 K. Rosberg 1...

                                                   5  \
0  1990 A. Senna 1991 A. Senna 1992 N. Mansell 19...

                                                   6  \
0  2000 M. Schumacher 2001 M. Schumacher 2002 M. ...

                                                   7  \
0  2010 S. Vettel 2011 S. Vettel 2012 S. Vettel 2...

                                                   8
0  2020 L. Hamilton 2021 M. Verstappen 2022 M. Ve...

In [11]:
# Let's settle for table 3 
table3 = df[3]

# Display the first 5 rows of table 3   
table3.head()

               Driver  Titles                                 Season(s)
0  Michael Schumacher     7.0  1994, 1995, 2000, 2001, 2002, 2003, 2004
1      Lewis Hamilton     7.0  2008, 2014, 2015, 2017, 2018, 2019, 2020
2  Juan Manuel Fangio     5.0              1951, 1954, 1955, 1956, 1957
3         Alain Prost     4.0                    1985, 1986, 1989, 1993
4    Sebastian Vettel     4.0                    2010, 2011, 2012, 2013

### Analyzing Data

`info` method gives you more details about the data and data types

In [12]:
# Using the json file from the previous example
filePath = 'data/Comparative.json' 

df = pd.read_json(filePath)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              127 non-null    datetime64[ns]
 1   Customer_Id       128 non-null    int64
 2   Customer_Name     128 non-null    object
 3   MRC_Client        128 non-null    float64
 4   MRC_Rev           127 non-null    float64
 5   MRC_Diff          127 non-null    float64
 6   MRC_Abs_Diff      127 non-null    float64
 7   NRC_Client        128 non-null    int64
 8   NRC_Rev           127 non-null    float64
 9   NRC_Diff          127 non-null    float64
 10  NRC_Abs_Diff      127 non-null    float64
 11  Usage_Client      128 non-null    float64
 12  Usage_Rev         127 non-null    float64
 13  Usage_Diff        127 non-null    float64
 14  Usage_Abs_Diff    127 non-null    float64
 15  Credits_Client    128 non-null    int64
 16  Credits_Rev       127 non-null    float64
 17  Credits_Diff      127 non-null    float64
 18  Credits_Abs_Diff  127 non-null    float64
 19  Taxes_Client      128 non-null    float64
 20  Taxes_Rev         127 non-null    float64
 21  Taxes_Diff        127 non-null    float64
 22  Taxes_Abs_Diff    127 non-null    float64
 23  Total_Client      128 non-null    float64
 24  Total_Rev         127 non-null    float64
 25  Total_Diff        127 non-null    float64
 26  Total_Abs_Diff    127 non-null    float64
dtypes: datetime64[ns](1), float64(22), int64(3), object(1)
memory usage: 27.1+ KB

`describe()` method gives stats on the dataframe

In [13]:
df.describe()  # Display summary statistics of the DataFrame

,Date,Customer_Id,MRC_Client,MRC_Rev,MRC_Diff,MRC_Abs_Diff,NRC_Client,NRC_Rev,NRC_Diff,NRC_Abs_Diff,...,Credits_Diff,Credits_Abs_Diff,Taxes_Client,Taxes_Rev,Taxes_Diff,Taxes_Abs_Diff,Total_Client,Total_Rev,Total_Diff,Total_Abs_Diff
count,127,1.280000e+02,128.000000,127.000000,127.000000,127.000000,128.0,127.0,127.0,127.0,...,127.0,127.0,128.000000,127.000000,127.000000,127.000000,128.000000,127.000000,127.000000,127.000000
mean,2024-09-01 00:00:00,1.100000e+09,1811.003438,1828.066535,4.282677,36.480472,0.0,0.0,0.0,0.0,...,0.0,0.0,341.933359,342.217087,-2.287165,100.497402,2181.133516,2198.139921,1.433071,125.788031
min,2024-09-01 00:00:00,1.100000e+09,-20.970000,7.010000,-626.250000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,-5.050000,1.370000,-1502.980000,0.000000,-26.020000,10.030000,-1709.620000,0.030000
25%,2024-09-01 00:00:00,1.100000e+09,233.102500,248.015000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,34.862500,48.950000,-50.770000,9.915000,271.675000,309.395000,-64.695000,9.865000
50%,2024-09-01 00:00:00,1.100000e+09,716.540000,744.040000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,143.990000,146.170000,-3.080000,37.450000,913.745000,909.640000,-1.490000,42.300000
75%,2024-09-01 00:00:00,1.100000e+09,1624.237500,1610.245000,4.040000,4.040000,0.0,0.0,0.0,0.0,...,0.0,0.0,292.447500,282.770000,17.270000,90.055000,1919.667500,1832.510000,24.510000,102.890000
max,2024-09-01 00:00:00,1.100000e+09,54355.630000,54860.630000,1085.040000,1085.040000,0.0,0.0,0.0,0.0,...,0.0,0.0,5647.210000,5871.940000,2452.140000,2452.140000,60010.060000,60353.550000,2456.180000,2456.180000
std,NaN,7.522719e+01,5162.021284,5205.619175,133.278819,128.219903,0.0,0.0,0.0,0.0,...,0.0,0.0,725.292869,795.276723,287.458897,269.180248,5850.166935,5899.397601,342.229876,318.080418

### Column Operations

In [49]:
# Create a DataFrame with some sample data
df = create_dataframe()

columns = ['Name', 'Age']

df[columns]  # Display only the specified columns

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [50]:
# Change the name of a column
df.rename(columns={'Name': 'Full Name'}, inplace=True) # inplace=True modifies the DataFrame directly
df

  Full Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2   Charlie   35      Chicago

In [51]:
# Add a new column to the DataFrame
df['Country'] = ['USA', 'USA', 'USA']
df

  Full Name  Age         City Country
0     Alice   25     New York     USA
1       Bob   30  Los Angeles     USA
2   Charlie   35      Chicago     USA

In [ ]:
# Subtract 5 from the 'Age' column
df['Age'] = df['Age'] - 5

# df['Age'] -= 5  # Another way to subtract 5 from the 'Age' column

df

  Full Name  Age         City Country
0     Alice   20     New York     USA
1       Bob   25  Los Angeles     USA
2   Charlie   30      Chicago     USA

In [53]:
# Remove the Country column
df.drop(columns=['Country'], inplace=True)
df

  Full Name  Age         City
0     Alice   20     New York
1       Bob   25  Los Angeles
2   Charlie   30      Chicago

In [55]:
# Change the name on the first row to 'Alicia' 
df.loc[0, 'Full Name'] = 'Alicia'
df

  Full Name  Age         City
0    Alicia   20     New York
1       Bob   25  Los Angeles
2   Charlie   30      Chicago

### Filtering by Value

In [56]:
# Create a DataFrame with some sample data
df = create_dataframe()

df[df['Age'] >= 30]  # Filter rows where Age is greater than or equal to 30

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
# Get a list of names in the DataFrame where the City contains the letter 'e' and print out the names with a message 

letter = 'e'

names_with_letter = df[df['City'].str.contains(letter)]['Name']

for name in names_with_letter:
    
    print(f"{name} lives in a city that contains the letter '{letter}'.")

Alice lives in a city that contains the letter 'e'.
Bob lives in a city that contains the letter 'e'.

### iterrows()

In [ ]:
# Create a DataFrame with some sample data and iterate through its rows

df = create_dataframe()

template = 'Row {ix}: {name} is {age} years old and lives in {city}.'

for index, row in df.iterrows():

    print(template.format(ix=index, name=row['Name'], age=row['Age'], city=row['City']))

Row 0: Alice is 25 years old and lives in New York.
Row 1: Bob is 30 years old and lives in Los Angeles.
Row 2: Charlie is 35 years old and lives in Chicago.